version: '3.1'

services:

  mysql:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql



  mysql2:
    image: mysql
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data2:/var/lib/mysql

  app:
    image: my-app:0.0.1
    restart: always
    environment:
      DB_CONNECTION_IP: mysql
    ports:
      - "8080:8080"

#  hello-docker2:
#    image: service2:0.0.1
#    restart: always
#    environment:
#      DB_CONNECTION_IP: mysql2
#    ports:
#      - "9000:9000"

volumes:
  mysql_data:
  mysql_data2: