# yaml json un superseti hesab olunur
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hello-counter
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  #    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: &connectionUrl jdbc:mysql://${DB_CONNECTION_IP:localhost}:${DB_CONNECTION_PORT:3306}/helloCounter?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
#    username: &username ${DB_CONNECTION_USERNAME:root}
#    password: &password ${DB_CONNECTION_PASSWORD:password}

  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    show-sql: true
    properties.hibernate.format_sql: true
#    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL81Dialect
